In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv(r"C:\Users\ajay\Desktop\T3.csv")
df

,country,country_long,name,gppd_idnr,capacity_mw,latitude,longitude,primary_fuel,other_fuel1,other_fuel2,...,year_of_capacity_data,generation_gwh_2013,generation_gwh_2014,generation_gwh_2015,generation_gwh_2016,generation_gwh_2017,generation_gwh_2018,generation_gwh_2019,generation_data_source,estimated_generation_gwh
0,IND,India,ACME Solar Tower,WRI1020239,2.5,28.1839,73.2407,Solar,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,IND,India,ADITYA CEMENT WORKS,WRI1019881,98.0,24.7663,74.6090,Coal,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,IND,India,AES Saurashtra Windfarms,WRI1026669,39.2,21.9038,69.3732,Wind,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,IND,India,AGARTALA GT,IND0000001,135.0,23.8712,91.3602,Gas,NaN,NaN,...,2019.0,NaN,617.789264,843.74700,886.004428,663.774500,626.239128,NaN,Central Electricity Authority,NaN
4,IND,India,AKALTARA TPP,IND0000002,1800.0,21.9603,82.4091,Coal,Oil,NaN,...,2019.0,NaN,3035.550000,5916.37000,6243.000000,5385.579736,7279.000000,NaN,Central Electricity Authority,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147,IND,India,CHHABRA TPS,IND0000081,2320.0,24.6217,77.0357,Coal,Oil,NaN,...,2019.0,NaN,4088.539000,3991.51200,6133.784000,6870.637949,9478.000000,NaN,Central Electricity Authority,NaN
148,IND,India,CHIBRO (YAMUNA),IND0000082,240.0,30.5559,77.7915,Hydro,NaN,NaN,...,2019.0,NaN,867.739500,809.71110,710.430000,779.652150,805.482350,NaN,Central Electricity Authority,NaN
149,IND,India,CHILLA,IND0000083,144.0,29.9760,78.2203,Hydro,NaN,NaN,...,2019.0,NaN,796.487550,749.90165,765.503250,807.601700,629.247950,NaN,Central Electricity Authority,NaN
150,IND,India,CHUTAK,IND0000084,44.0,34.4903,76.1137,Hydro,NaN,NaN,...,2019.0,NaN,35.322500,36.72545,43.899400,45.491400,48.715200,NaN,Central Electricity Authority,NaN
151,IND,India,CHUZACHEN,IND0000085,110.0,27.2093,88.6659,Hydro,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
# Average Electrical generation capacity(capacity_mw) according to the primary_fuel type
df.groupby(['primary_fuel']).agg({'capacity_mw':'mean'})

              capacity_mw
primary_fuel
Biomass         17.100000
Coal           603.713462
Gas            255.555000
Hydro          166.130952
Oil             55.566667
Solar           11.923077
Wind            40.340000

In [ ]:
# Creating a new Dataframe by removing the null values in latitude and longitude
mes=df.loc[df['latitude'].notna()==True]

In [65]:
import warnings
warnings.filterwarnings('ignore')
# Prediction Primary Fuel according to Capacity_mw
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
y=OrdinalEncoder().fit_transform(mes['primary_fuel'].to_numpy()[:,np.newaxis]).ravel()
X=mes.loc[:,['capacity_mw','latitude','longitude']]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)
for estimators in [SVC(class_weight='balanced'),DecisionTreeClassifier(class_weight='balanced'),KNeighborsClassifier(),RandomForestClassifier(class_weight='balanced')]:
    model=estimators
    #Identifying the parameters of an algorithm
    model.get_params()
   # Passing the model parameters to train the dataset
    model.fit(X_train,y_train)
   # Validating the model using test dataset
    y_pred=model.predict(X_test)
    # Finding the Accuracy of the model
    print(estimators,':',accuracy_score(y_test,y_pred))
   # Classification Report 
    print(classification_report(y_test,y_pred))
  # Predicting power
    print(model.predict(mes.loc[:,['capacity_mw','latitude','longitude']]))

# Even if the accuracy score is less SVC estimator predicting the right

SVC(class_weight='balanced') : 0.32432432432432434
              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00         3
         1.0       1.00      0.33      0.50        15
         2.0       0.00      0.00      0.00         1
         3.0       0.00      0.00      0.00         7
         4.0       0.00      0.00      0.00         0
         5.0       0.41      1.00      0.58         7
         6.0       0.00      0.00      0.00         4

    accuracy                           0.32        37
   macro avg       0.20      0.19      0.15        37
weighted avg       0.48      0.32      0.31        37

[5. 5. 5. 4. 1. 2. 5. 4. 2. 4. 1. 4. 1. 5. 1. 2. 2. 1. 5. 5. 5. 2. 2. 5.
 5. 5. 5. 4. 5. 5. 5. 5. 5. 5. 5. 5. 5. 2. 5. 2. 4. 1. 2. 5. 5. 2. 2. 5.
 2. 5. 5. 5. 5. 1. 5. 2. 5. 1. 5. 2. 4. 2. 5. 5. 2. 5. 5. 5. 5. 1. 5. 5.
 1. 5. 5. 5. 5. 5. 2. 5. 5. 5. 5. 2. 2. 5. 5. 1. 5. 5. 2. 5. 2. 5. 5. 2.
 4. 2. 5. 5. 4. 2. 5. 5. 2. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.
 4. 5. 5. 5. 5. 5. 5. 5. 2. 2. 2. 5. 5. 2. 4. 5. 2. 1. 5. 5. 5. 1. 2. 4.
 5. 4.]
DecisionTreeClassifier(class_weight='balanced') : 0.7297297297297297
              precision    recall  f1-score   support

         0.0       1.00      0.67      0.80         3
         1.0       0.79      1.00      0.88        15
         2.0       0.00      0.00      0.00         1
         3.0       0.43      0.43      0.43         7
         5.0       0.86      0.86      0.86         7
         6.0       0.50      0.25      0.33         4

    accuracy                           0.73        37
   macro avg       0.60      0.53      0.55        37
weighted avg       0.70      0.73      0.70        37

[5. 1. 6. 2. 1. 1. 3. 3. 3. 1. 1. 3. 1. 3. 1. 2. 1. 1. 0. 1. 0. 2. 1. 1.
 5. 6. 3. 3. 6. 6. 5. 5. 5. 5. 5. 5. 5. 1. 0. 3. 3. 1. 1. 1. 1. 1. 1. 3.
 3. 3. 3. 3. 1. 1. 2. 1. 3. 1. 1. 1. 1. 3. 3. 6. 1. 0. 0. 1. 1. 1. 3. 1.
 3. 1. 0. 3. 3. 3. 1. 3. 3. 3. 1. 1. 3. 3. 3. 1. 0. 1. 1. 1. 1. 5. 3. 1.
 1. 1. 6. 4. 2. 1. 3. 4. 1. 5. 5. 6. 5. 5. 5. 5. 5. 5. 5. 5. 6. 6. 6. 6.
 3. 5. 3. 5. 5. 5. 5. 1. 3. 3. 3. 1. 1. 1. 1. 1. 1. 1. 1. 6. 3. 1. 3. 3.
 3. 3.]
KNeighborsClassifier() : 0.4864864864864865
              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00         3
         1.0       0.56      0.67      0.61        15
         2.0       0.00      0.00      0.00         1
         3.0       0.33      0.43      0.38         7
         5.0       0.83      0.71      0.77         7
         6.0       0.00      0.00      0.00         4

    accuracy                           0.49        37
   macro avg       0.29      0.30      0.29        37
weighted avg       0.45      0.49      0.46        37

[5. 1. 6. 2. 1. 1. 1. 3. 3. 3. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1.
 5. 6. 1. 1. 6. 3. 5. 5. 5. 5. 5. 5. 5. 1. 0. 1. 3. 1. 1. 1. 5. 3. 3. 3.
 3. 3. 1. 3. 5. 1. 1. 1. 1. 1. 1. 1. 1. 3. 3. 0. 3. 0. 3. 6. 6. 1. 0. 1.
 1. 1. 1. 1. 3. 3. 1. 3. 3. 3. 3. 1. 3. 3. 1. 1. 5. 1. 1. 3. 1. 5. 1. 1.
 3. 1. 6. 1. 3. 1. 3. 3. 1. 5. 5. 6. 5. 5. 5. 5. 5. 5. 6. 5. 5. 5. 0. 1.
 2. 5. 1. 5. 6. 5. 5. 3. 3. 1. 1. 1. 6. 1. 1. 1. 1. 1. 3. 6. 3. 1. 1. 2.
 3. 1.]
RandomForestClassifier(class_weight='balanced') : 0.7027027027027027
              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00         3
         1.0       0.67      0.93      0.78        15
         2.0       0.00      0.00      0.00         1
         3.0       0.83      0.71      0.77         7
         5.0       1.00      0.86      0.92         7
         6.0       0.33      0.25      0.29         4

    accuracy                           0.70        37
   macro avg       0.47      0.46      0.46        37
weighted avg       0.65      0.70      0.67        37

[5. 1. 6. 2. 1. 1. 3. 3. 3. 1. 1. 3. 1. 3. 1. 2. 1. 1. 1. 1. 0. 2. 1. 1.
 5. 6. 1. 3. 6. 6. 5. 5. 5. 5. 5. 5. 5. 1. 0. 3. 3. 1. 1. 1. 1. 1. 1. 3.
 3. 3. 3. 3. 1. 1. 2. 1. 3. 1. 1. 1. 1. 3. 3. 6. 1. 0. 6. 1. 1. 1. 3. 1.
 3. 1. 0. 3. 3. 3. 1. 3. 3. 3. 1. 1. 3. 3. 3. 1. 0. 1. 1. 1. 1. 3. 3. 1.
 1. 2. 6. 4. 2. 1. 3. 4. 1. 5. 5. 6. 5. 5. 5. 5. 5. 5. 5. 5. 6. 6. 6. 6.
 1. 5. 1. 5. 5. 5. 5. 1. 3. 3. 3. 1. 1. 1. 1. 1. 1. 1. 3. 6. 3. 1. 3. 3.
 3. 3.]

In [76]:
wes=df.loc[df['generation_gwh_2014'].notna()==True,['capacity_mw','primary_fuel','generation_gwh_2014', 'generation_gwh_2015',
       'generation_gwh_2016', 'generation_gwh_2017', 'generation_gwh_2018',]]
new=pd.concat([wes.loc[:,['capacity_mw','generation_gwh_2014', 'generation_gwh_2015',
       'generation_gwh_2016', 'generation_gwh_2017', 'generation_gwh_2018']],pd.get_dummies(wes['primary_fuel'])],axis=1)

In [78]:
new.loc[new['Gas']==1]

,capacity_mw,generation_gwh_2014,generation_gwh_2015,generation_gwh_2016,generation_gwh_2017,generation_gwh_2018,Coal,Gas,Hydro,Oil
3,135.00,617.789264,843.747000,886.004428,663.77450,626.239128,0,1,0,0
16,419.33,1611.987000,909.000000,666.420000,430.00000,528.280000,0,1,0,0
22,652.00,1607.000000,1465.000000,509.000000,357.00000,521.000000,0,1,0,0
58,42.00,304.832800,231.626436,187.193669,178.10669,173.720000,0,1,0,0
64,120.00,2.853870,8.295912,10.468980,5.85771,0.056000,0,1,0,0
106,165.00,145.560000,3.417200,0.000000,60.71800,0.000000,0,1,0,0

In [79]:
new.corr()

,capacity_mw,generation_gwh_2014,generation_gwh_2015,generation_gwh_2016,generation_gwh_2017,generation_gwh_2018,Coal,Gas,Hydro,Oil
capacity_mw,1.000000,0.823856,0.892150,0.912388,0.910862,0.917718,0.578468,-0.129846,-0.447485,-0.131911
generation_gwh_2014,0.823856,1.000000,0.949625,0.896970,0.877882,0.846872,0.524527,-0.143897,-0.385794,-0.133047
generation_gwh_2015,0.892150,0.949625,1.000000,0.939545,0.936456,0.905655,0.585095,-0.169808,-0.430082,-0.133583
generation_gwh_2016,0.912388,0.896970,0.939545,1.000000,0.978471,0.965118,0.576960,-0.181886,-0.418348,-0.124040
generation_gwh_2017,0.910862,0.877882,0.936456,0.978471,1.000000,0.988591,0.573266,-0.188150,-0.412073,-0.121120
generation_gwh_2018,0.917718,0.846872,0.905655,0.965118,0.988591,1.000000,0.540447,-0.170483,-0.393701,-0.110768
Coal,0.578468,0.524527,0.585095,0.576960,0.573266,0.540447,1.000000,-0.266046,-0.776991,-0.148564
Gas,-0.129846,-0.143897,-0.169808,-0.181886,-0.188150,-0.170483,-0.266046,1.000000,-0.302122,-0.057767
Hydro,-0.447485,-0.385794,-0.430082,-0.418348,-0.412073,-0.393701,-0.776991,-0.302122,1.000000,-0.168710
Oil,-0.131911,-0.133047,-0.133583,-0.124040,-0.121120,-0.110768,-0.148564,-0.057767,-0.168710,1.000000

In [87]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
X=new.drop(['capacity_mw'],axis=1)
y=new['capacity_mw']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=42)
reg=LinearRegression()
reg.fit(X_train,y_train)
y_prd=reg.predict(X_test)
print(r2_score(y_test,y_prd))

0.720340612260746

In [90]:
pd.DataFrame([y_test.values,y_prd]).T

         0            1
0    600.0   391.597012
1   2920.0  2038.347284
2    135.0   256.808841
3     75.0   129.470313
4    290.0   101.927364
5   1379.0   531.368607
6    180.0    95.422095
7    652.0   322.174659
8    720.0   286.879037
9    240.0   203.305741
10   231.0   226.413199
11  1200.0  1254.355280
12    30.0   134.860452
13   600.0   290.401544
14  1700.0   828.918340
15   750.0   953.638574
16    60.0   103.848351
17  1050.0   898.118261
18   165.0   145.462494
19   134.0   114.622507
20   210.0   447.233642
21    25.2    58.991328